eureka:
  client:
    service-url:
     defaultZone: http://127.0.0.1:1111/eureka/
    register-with-eureka: true
    fetch-registry: true
  server:
    eviction-interval-timer-in-ms: 1000
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
ribbon:
  ReadTimeout: 30000
feign:
  hystrix:
    enabled: true
  compression:
    request:
      min-request-size: 512

## 刷新时，关闭安全验证
management:
  security:
    enabled: false
server:
  port: 8080
spring:
  application:
    name: test02-service