server:
  port: 18801
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:1111/eureka/
  instance:
    prefer-ip-address: true
  server:
    eviction-interval-timer-in-ms: 1000
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
ribbon:
  ReadTimeout: 30000
feign:
  hystrix:
    enabled: true
spring:
  application:
    name: test-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: lmy
    password: 165177
    virtual-host: testHost

