server:
  port: 18888
spring:
  application:
    name: zipkin-server
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:1111/eureka/
  instance:
    prefer-ip-address: true
  server:
    eviction-interval-timer-in-ms: 10000
    enable-self-preservation: false
