server:
  port: 9988
spring:
  cloud:
    config:
      server:
        git:
          uri:
          username:
          password:
          search-paths: '/config-repo/{profile}'
          # 修改默认分支到dev
          default-label: dev
  application:
    name: config-server