server:
  port: 1111
spring:
  application:
    name: eureka
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: false
    service-url:
     defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    fetch-registry: false
  server:
    eviction-interval-timer-in-ms: 10000
    enable-self-preservation: false

security:
  basic:
    enabled: false
  user:
    name: lmy
    password: 165177